apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: uplink-kafka
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-headless
spec:
  clusterIP: None
  selector:
    app: uplink-kafka
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: 9092
