apiVersion: v1
kind: Service
metadata:
  name: uplink-minio
spec:
  ports:
    - name: s3
      port: {{ .Values.service.port }}
      targetPort: 9000
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: 9001
  selector:
    app: uplink-minio
