apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: uplink-keycloak
spec:
  selector:
    app: uplink-keycloak
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
